# Generated by Django 3.0.8 on 2020-12-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='lol',
            name='name',
            field=models.CharField(default='lolz', max_length=50),
        ),
    ]
