# Generated by Django 3.0.8 on 2020-12-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_lol_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lol',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
