# Generated by Django 3.0.8 on 2020-12-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
