# Generated by Django 3.0.8 on 2020-12-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_task_overdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(max_length=3000),
        ),
    ]
