# Generated by Django 3.0.8 on 2021-01-04 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20210104_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='CustomList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.CustomList'),
        ),
    ]
