# Generated by Django 3.0.8 on 2021-01-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20210104_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
