# Generated by Django 3.0.8 on 2021-01-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_task_lol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='lol',
        ),
    ]
